### ISSUE TITLE
Internal Test App solr configuration causes RSolr::Error::Http - 404 Not Found Error

### ISSUE THREAD

**Issue by dgcliff** [projectblacklight/blacklight-access_controls#52]
## Steps to reproduce

Running the README's steps for starting the internal test app as below;

```
$ bundle exec rake solr:clean
$ bundle exec rake solr:start
$ bundle exec rake engine_cart:generate
$ bundle exec rake engine_cart:server
```

Navigating to `http://localhost:3000/` causes

```
Blacklight::Exceptions::InvalidRequest (RSolr::Error::Http - 404 Not Found
Error:     Not Found

URI: http://127.0.0.1:8983/solr/blacklight-core/select?wt=json&facet.field=format&facet.field=%7B%21ex%3Dpub_date_ssim_single%7Dpub_date_ssim&facet.field=subject_ssim&facet.field=language_ssim&facet.field=lc_1letter_ssim&facet.field=subject_geo_ssim&facet.field=subject_era_ssim&facet.query=pub_date_ssim%3A%5B2014+TO+*%5D&facet.query=pub_date_ssim%3A%5B2009+TO+*%5D&facet.query=pub_date_ssim%3A%5B1994+TO+*%5D&facet.pivot=format%2Clanguage_ssim&&&rows=10&facet=true&f.subject_ssim.facet.limit=21&f.language_ssim.facet.limit=11&sort=score+desc%2C+pub_date_si+desc%2C+title_si+asc

Backtrace: /home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rsolr-2.2.1/lib/rsolr/client.rb:206:in `rescue in execute'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rsolr-2.2.1/lib/rsolr/client.rb:196:in `execute'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rsolr-2.2.1/lib/rsolr/client.rb:191:in `send_and_receive'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/blacklight-7.0.1/lib/blacklight/solr/repository.rb:62:in `block in send_and_receive'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/benchmarkable.rb:43:in `block in benchmark'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/core_ext/benchmark.rb:14:in `ms'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/benchmarkable.rb:43:in `benchmark'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/blacklight-7.0.1/lib/blacklight/solr/repository.rb:60:in `send_and_receive'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/blacklight-7.0.1/lib/blacklight/solr/repository.rb:23:in `search'):

blacklight (7.0.1) lib/blacklight/solr/repository.rb:73:in `rescue in send_and_receive'
```

## Cause of issue

Investigating the dir `/tmp/tmp/solr-7.7.1` created by `solr_wrapper`'s `bundle exec rake solr:clean` rake task shows that there are no cores, and no config files.

```
vagrant@vagrant-ubuntu-trusty-64:/tmp/solr-7.7.1/server/solr$ ls -lah
total 24K
drwxrwxr-x  3 vagrant vagrant 4.0K Mar 13 18:57 .
drwxrwxr-x 11 vagrant vagrant 4.0K Mar 13 18:57 ..
drwxrwxr-x  4 vagrant vagrant 4.0K Mar 13 18:57 configsets
-rw-rw-r--  1 vagrant vagrant 3.1K Mar 13 18:57 README.txt
-rw-rw-r--  1 vagrant vagrant 2.2K Mar 13 18:57 solr.xml
-rw-rw-r--  1 vagrant vagrant 1006 Mar 13 18:57 zoo.cfg
vagrant@vagrant-ubuntu-trusty-64:/tmp/solr-7.7.1/server/solr$
```

The step in the README that appears to have previously done this provisioning `$ bundle exec rake solr:config` is not available. I'm assuming it was from a previous version of `solr_wrapper`.

## Potential solution
I'm working on a pull request that will adjust the use of `solr_wrapper` to properly configure solr

**Comment by dgcliff** [comment]
## Secondary Issue

Looking to blacklight for guidance on `solr_wrapper` configuration and invocation reveals that even when solr is run via `bundle exec solr_wrapper` and the conf directory is correctly applied, and `blacklight-core` is created, navigating to `http://localhost:3000/` causes a 400 Bad Request.

```
Completed 500 Internal Server Error in 771ms (ActiveRecord: 0.0ms)



Blacklight::Exceptions::InvalidRequest (RSolr::Error::Http - 400 Bad Request
Error: {
  "responseHeader":{
    "status":400,
    "QTime":524,
    "params":{
      "f.subject_ssim.facet.limit":"21",
      "facet.query":["pub_date_ssim:[2014 TO *]",
        "pub_date_ssim:[2009 TO *]",
        "pub_date_ssim:[1994 TO *]"],
      "f.language_ssim.facet.limit":"11",
      "facet.field":["format",

URI: http://127.0.0.1:8983/solr/blacklight-core/select?wt=json&facet.field=format&facet.field=%7B%21ex%3Dpub_date_ssim_single%7Dpub_date_ssim&facet.field=subject_ssim&facet.field=language_ssim&facet.field=lc_1letter_ssim&facet.field=subject_geo_ssim&facet.field=subject_era_ssim&facet.query=pub_date_ssim%3A%5B2014+TO+*%5D&facet.query=pub_date_ssim%3A%5B2009+TO+*%5D&facet.query=pub_date_ssim%3A%5B1994+TO+*%5D&facet.pivot=format%2Clanguage_ssim&&&rows=10&facet=true&f.subject_ssim.facet.limit=21&f.language_ssim.facet.limit=11&sort=score+desc%2C+pub_date_si+desc%2C+title_si+asc

Backtrace: /home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rsolr-2.2.1/lib/rsolr/client.rb:206:in `rescue in execute'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rsolr-2.2.1/lib/rsolr/client.rb:196:in `execute'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rsolr-2.2.1/lib/rsolr/client.rb:191:in `send_and_receive'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/blacklight-7.0.1/lib/blacklight/solr/repository.rb:62:in `block in send_and_receive'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/benchmarkable.rb:43:in `block in benchmark'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/core_ext/benchmark.rb:14:in `ms'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.2.1/lib/active_support/benchmarkable.rb:43:in `benchmark'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/blacklight-7.0.1/lib/blacklight/solr/repository.rb:60:in `send_and_receive'
/home/vagrant/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/blacklight-7.0.1/lib/blacklight/solr/repository.rb:23:in `search'):

blacklight (7.0.1) lib/blacklight/solr/repository.rb:73:in `rescue in send_and_receive'
```

I believe this is because the conf found at `https://github.com/projectblacklight/blacklight-access_controls/tree/master/solr_conf/conf` isn't correct.
